# Dependencies
markdown:         kramdown
highlighter:      rouge

# Gems
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            No Agenda Github
tagline:          'Be a code-donor, not a boner'
description:      'A repository of <a href="http://www.noagendashow.com/" target="_blank">No Agenda podcast</a> content and open-source software projects for the best podcast in the universe. Made by <a href="https://github.com/reelsense" target="_blank">@reelsense</a>.'
url:              https://no-agenda.github.io/
baseurl:          https://no-agenda.github.io/

author:
  name:           'Bryan'
  url:            http://bringyourwallet.com/


# Custom vars
version:          1.2

github:
  repo:           https://github.com/No-Agenda/
